/**
 * @fileoverview Reschedule type definitions and Zod schemas for AI-generated reschedule options
 * @module types/reschedule
 */

import { z } from 'zod';

/**
 * Schema for a single reschedule option generated by AI
 */
export const rescheduleOptionSchema = z.object({
  suggestedDate: z.string().datetime(),
  suggestedDuration: z.number().positive(),
  reasoning: z.string(),
  weatherSummary: z.object({
    temperature: z.number(),
    windSpeed: z.number(),
    visibility: z.number(),
    conditions: z.string(),
  }),
  confidenceScore: z.number().min(0).max(100),
});

/**
 * Type for a single reschedule option
 */
export type RescheduleOption = z.infer<typeof rescheduleOptionSchema>;

/**
 * Schema for AI reschedule response containing 3 options
 */
export const aiRescheduleResponseSchema = z.object({
  options: z.array(rescheduleOptionSchema).length(3),
  analysisNote: z.string(),
});

/**
 * Type for AI reschedule response
 */
export type AIRescheduleResponse = z.infer<typeof aiRescheduleResponseSchema>;

